@baseUrl = http://localhost:5000/api
@deployedUrl =https://nest-js-ecommerce.onrender.com/api
@bearetoken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJlbWFpbCI6IlJheW1vbmRfV2Fsc2hAeWFob28uY29tIiwicm9sZSI6IkNVU1RPTUVSIiwiaWF0IjoxNzQ4NTAyMzg3LCJleHAiOjE3NDg1ODg3ODd9.yN31HNG484nAW4P1B454FpwnsftvN94vBtbGXZwSLnE

GET {{deployedUrl}}/users
Authorization: Bearer {{bearetoken}}

###
GET {{deployedUrl}}/reviews/10
Authorization: Bearer {{bearetoken}}


###
POST  {{deployedUrl}}/auth/register
Content-Type: application/json

{
    "email": "test5@example.com",
    "password": "SecurePassword123!",
    "firstName": "Daniel",
    "lastName": "Kavatha"
}
###
PATCH   {{baseUrl}}/users/12
Content-Type: application/json

{
    "email": "Hyatt@yahoo.com"
}

###
DELETE {{baseUrl}}/users/15
Authorization: Bearer {{bearetoken}}

###
POST {{deployedUrl}}/auth/login
Content-Type: application/json

{
    "email": "test5@example.com",
    "password": "SecurePassword123!"
}
###
PATCH   {{baseUrl}}/users/12
Content-Type: application/json
Authorization: Bearer {{bearetoken}}

{
    "email": "edittest@example.com"
    
}
###
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "SecurePassword123!"
}

###
GET {{baseUrl}}/reviews
Authorization: Bearer {{bearetoken}}

###
GET {{baseUrl}}/products/21
Authorization: Bearer {{bearetoken}}

###
POST {{baseUrl}}/products
Authorization: Bearer {{bearetoken}}
Content-Type: application/json

{
  "name": "Laptop Pro",
  "description": "High-performance laptop for professionals.",
  "price": 120,
  "stockQuantity": 75,
  "images": [
        "URL_ADDRESS.com/laptop1.jpg",
  ],
  "sku": "LAPP-2025-002",
  "isActive": true,
  "categoryId": 2
}
###

###
PATCH {{baseUrl}}/products/21
Authorization: Bearer {{bearetoken}}
Content-Type: application/json

{
  "name": "Lenovo Thinkpad",
  "description": "High-performance laptop for professionals."
}

#########################################################################
                ORDER ENDPOINTS
##########################################################################
###
GET {{baseUrl}}/orders
Authorization: Bearer {{bearetoken}}

###
GET {{baseUrl}}/orders/28
Authorization: Bearer {{bearetoken}}

###
POST {{baseUrl}}/orders
Authorization: Bearer {{bearetoken}}
Content-Type: application/json

{
  "userId": 6,
  "subtotal": 120.75,
  "tax": 9.66,
  "shipping": 5.00,
  "total": 135.41,
  "shippingAddress": {
    "firstName": "John",
    "lastName": "Doe",
    "street": "123 Main St",
    "city": "Anytown",
    "state": "CA",
    "zipCode": "90210",
    "country": "USA"
  },
  "billingAddress": {
    "firstName": "John",
    "lastName": "Doe",
    "street": "123 Main St",
    "city": "Anytown",
    "state": "CA",
    "zipCode": "90210",
    "country": "USA"
  },
  "orderItems": [
    {
      "price": 21,
      "productId": 11,
      "quantity": 2
    }
  ]
}

###
PATCH {{baseUrl}}/orders/28
Authorization: Bearer {{bearetoken}}
Content-Type: application/json

{
  "tax": 4.50,
  "shipping": 2.50,
  "total": 139.91
}

###
DELETE {{baseUrl}}/orders/23
Authorization: Bearer {{bearetoken}}

