@baseUrl = http://localhost:5000/api
@bearetoken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJlbWFpbCI6IlJheW1vbmRfV2Fsc2hAeWFob28uY29tIiwicm9sZSI6IkNVU1RPTUVSIiwiaWF0IjoxNzQ4NTAyMzg3LCJleHAiOjE3NDg1ODg3ODd9.yN31HNG484nAW4P1B454FpwnsftvN94vBtbGXZwSLnE

GET {{baseUrl}}/users
Authorization: Bearer {{bearetoken}}

###
POST  {{baseUrl}}/auth/register
Content-Type: application/json

{
    "email": "test2@example.com",
    "password": "SecurePassword123!",
    "firstName": "Daniel",
    "lastName": "Kavatha",
    "phone": "123-456-7890"
    
}

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "Raymond_Walsh@yahoo.com",
    "password": "password123"
}
###
PATCH   {{baseUrl}}/users/12
Content-Type: application/json

{
    "email": "edittest@example.com"
    
}
###
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "SecurePassword123!"
}
